### ISSUE TITLE
Sensitive info leaked in app.py

### ISSUE THREAD

**Issue by M786453** [jahanzaibbabar/Flask_Login_System#1]
Secrets such as API keys, database credentials, and other sensitive information should be stored securely to prevent unauthorized access. You should either use environment variables or config files.

**Comment by jahanzaibbabar** [comment]
Thanks for raising this issue.
Yes, it is really important to save the creds secretly to an environment or config file. I will fix it in the future. Btw, this project is just for educational purposes not for business use.

Your contribution will really appreciated.
